### ISSUE TITLE
Package release versioning

### ISSUE THREAD

**Issue by gbooth27** [tanaikech/go-gdoctableapp#1]
Hi @tanaikech 

Just wanted to say thanks for making this package, I was having a huge amount of trouble trying to manipulate tables with the Go API for Gdocs until I found this, which was exactly what I needed.

One thing i was wondering, do you think you could do official releases of this package? I can still use it as is now, but would be nice to have some semantic versioning so that I can more clearly tell which release I am running. (something like this https://github.com/sirupsen/logrus/releases) 

Thanks again!

Graham

**Comment by tanaikech** [comment]
Thank you for your comment. Now I created it. In the current stage, the start version is v1.1.0. Could you please confirm it?
[https://github.com/tanaikech/go-gdoctableapp/releases](https://github.com/tanaikech/go-gdoctableapp/releases)

**Comment by gbooth27** [comment]
looks good! thanks so much

**Comment by gbooth27** [comment]
actually sorry one last thing, for go packages the versioning requires 3 levels of specificity (X.Y.Z) so you would need to release it as 1.10.0 for it to work https://www.geeksforgeeks.org/introduction-semantic-versioning/ is a nice descriptor for what each level of version means (although looks like you may have meant to release it as `1.1.0` from your release notes, but I think you missed a `.` when you did the release)

**Comment by tanaikech** [comment]
Thank you for replying. Yes. I could notice my mistype by your replying. I modified it just now. And also, thank you for the information.
